### ISSUE TITLE
VersionAssemblyInfo.cs seems to be missing

### ISSUE THREAD

**Issue by nengberg** [Philo/cake-gulp#2]
Hi!

I forked your reposistory to extend/fix functionality and stumbled across a bug.

Source file 'C:\Projects\cake-gulp\src\Cake.Gulp..\VersionAssemblyInfo.cs' could not be found.

**Comment by Philo** [comment]
hi @nengberg, the `VersionAssemblyInfo.cs` file is generated by the build, if you run ./build.ps1 first it should be created

**Comment by nengberg** [comment]
Hi, thanks. Should it be included in the project file? If you just open up the project via Visual Studio and build it will not compile

**Comment by Philo** [comment]
The VersionAssemblyInfo.cs is generated from the Cake build (via GitVersion), the file is included in the VS solution so that the assembly version stamping happens, but excluded from git as its a generated and constantly changing item.

After you have cloned the repo, build it first (./build.ps1) and then you can open the solution without errors

**Comment by nengberg** [comment]
Yeah, that seems to work! I didn't know that you had to build via `build.ps1` before you could actually open it in Visual Studio. I close this issue
